Kill list implementation with a patch route
XLabsProject/master pull request #300
Opened 2022-08-03 13:44 UTC by Rackover

On iw4x - and maybe other clients - people use the master server to advertise their discord with locked servers or fake player count, we would like to have a way to handle these issues easily by banning target IPs from the master server.

This should be extremely simple to do and require no redeploy/pr/snake intervention, cause if it takes more effort to update the kill list than it takes malicious hosters to change their IP, it won't be useful.

So I implemented a very simple kill list TXT the server writes to and reads from, and that can be very easily updated with a patch command sent with a secret key (stored in ENV in serverside). Ultimately we could have the XLabs discord bot send that message on demand (so the bot would have the secret key), so that we could in the admin channel update the kill list with just a single discord message. Very neat!

The kill list also supports adding a reason to any kill line so that we can remember why a certain ip is removed or not.

2022-08-04 10:57 UTC, Emosewaj commented
I maintain the discord bot, I'd be happy to include a slash-command for this once it goes through. If this gets merged, hit me up on discord so we can talk specifics.

2022-08-07 11:46 UTC, momo5502 requested changes

2022-08-07 11:46 UTC, momo5502 commented on src/services/kill_list.cpp
> +void kill_list::add_to_kill_list(const kill_list::kill_list_entry& add)
const ref could be a moved object instead

2022-08-07 11:46 UTC, momo5502 commented on src/services/patch_kill_list_command.cpp
> +	auto result = getenv_s(&size, key_buff, 128, key_env_name.data());
why env and not a text file next to it, just like patreon key is read?

2022-08-07 11:46 UTC, momo5502 commented on src/services/kill_list.hpp
> +	std::recursive_mutex kill_list_mutex;
why recursive?

2022-08-07 11:46 UTC, momo5502 commented on src/services/kill_list.hpp
> +	std::unordered_map<std::string, kill_list_entry> entries;
there is a concurrency container class that wraps a container together with a mutex. pls use that.

2022-08-07 11:46 UTC, momo5502 commented on src/services/patch_kill_list_command.cpp
> +	if (supplied_address[0] == '-') // e.g.  -1.2.3.4 removes it from the list, while 1.2.3.4 adds it to the list
hm. a bit weird. why not add a param before that says add or remove

2022-08-07 11:46 UTC, momo5502 commented on src/services/patch_kill_list_command.cpp
> +	if (supplied_key == key)
why not use a asymetric cryptography scheme for that? like ecdsa? eg. a timestamp is signed with the private key and the server verifies it? or a simple challenge

2022-08-07 12:33 UTC, Rackover commented on src/services/patch_kill_list_command.cpp
> +	auto result = getenv_s(&size, key_buff, 128, key_env_name.data());
your choice! :p 
Didnt know what you preferred as a server admin. I do prefer env on my server software.
will make it a TXT instead then

2022-08-12 09:00 UTC, Rackover commented on src/services/patch_kill_list_command.cpp
> +	if (supplied_address[0] == '-') // e.g.  -1.2.3.4 removes it from the list, while 1.2.3.4 adds it to the list
well idk i prefer it this way, it makes one less param. if you want an explicit fourth param placed before that says "add" or "remove" i can do it too, what do you prefer ?

2022-08-12 19:41 UTC, momo5502 commented on src/services/patch_kill_list_command.cpp
> +	if (supplied_address[0] == '-') // e.g.  -1.2.3.4 removes it from the list, while 1.2.3.4 adds it to the list
the fact that you mentioned "explicit" shows why a fourth param is better. it is explicit and therefore easier to understand

2022-08-12 19:46 UTC, momo5502 reviewed
will check the rest tomorrow. i'm super tired right now.

2022-08-12 19:46 UTC, momo5502 commented on src/services/kill_list.cpp
> +	entries_container.access([str_address, &reason, &contains](const kill_list_entries& entries)
why are you copying the str_address? also why not just [&] ?

2022-08-12 19:46 UTC, momo5502 commented on src/services/kill_list.cpp
> +	entries_container.access([str_address, &reason, &contains](const kill_list_entries& entries)
access takes an optional return type, so return access<bool>(...)
that way you can simply return a bool instead of exfiltrating it from the lambda

2022-08-12 19:46 UTC, momo5502 commented on src/services/kill_list.cpp
> +				contains = true;
return true

2022-08-12 19:46 UTC, momo5502 commented on src/services/kill_list.cpp
> +				entries.emplace(add.ip_address, add);
std::move(add)

2022-08-18 12:10 UTC, Rackover commented
I tested all the features with a custom client and they're working as intended!
- Wrong signature refuses the command
- Any other 3nd argument than "add" or "remove" refuses the command
- Kill list can be updated (elements added or removed at will)
- An existing entry can be updated (you can update the reason by adding it again with a different reason)
- Connections present on the kill list correctly get refused
- KILL.TXT is correctly updated, only when necessary

I did not do a challenge like you said, I simply used the private key to sign the message (signing the IP argument more specifically) so that only someone with the server private key can patch the list, and the worst thing an eavesdropper could do is repeating a command 🙂 There is no longer a secret key to store or anything,  Is that OK with you ?

2022-08-18 12:45 UTC, diamante0018 commented on src/services/kill_list.cpp
> +				if (existing_entry != entries.end())
contains

2022-08-18 12:47 UTC, diamante0018 commented on src/services/kill_list.cpp
> +				std::string comment{};
{} not needed and weird in this context

2022-08-18 12:47 UTC, diamante0018 commented on src/services/kill_list.cpp
> +		for (auto kv : entries)
reference

2022-08-18 12:47 UTC, diamante0018 commented on src/services/kill_list.cpp
> +			auto entry = kv.second;
reference

2022-08-18 12:48 UTC, diamante0018 commented on src/services/kill_list.cpp
> +		console::info("Wrote %s to disk (%i entries)", kill_file.data(), entries.size());
size in unsigned, correct format string

2022-08-18 12:48 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +		throw execution_exception{ "Invalid parameter count" };
use () initializer

2022-08-18 12:48 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +		throw execution_exception{ "Invalid parameter #2: should be 'add' or 'remove'" };
same as above

2022-08-18 12:48 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +	std::string supplied_reason{};
remove {}

2022-08-18 12:48 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +	auto supplied_address = params[2];
reference

2022-08-18 12:49 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +		for (size_t i = 3; i < params.size(); i++)
++i

2022-08-18 12:49 UTC, diamante0018 commented on src/services/patch_kill_list_command.cpp
> +		throw execution_exception{ "Signature verification of the kill list patch key failed" };
same as above

2022-08-18 12:49 UTC, diamante0018 commented on src/std_include.hpp
> +#include <stdlib.h>
unused?

2022-08-18 14:57 UTC, Rackover commented on src/services/kill_list.cpp
> +			if (entries.find(str_address) != entries.end())
does not exist in ++17

2022-08-18 15:01 UTC, Rackover commented on src/services/kill_list.cpp
> +				if (existing_entry != entries.end())
not in c++17

2022-08-18 16:03 UTC, diamante0018 reviewed
The code generally looks okay, made some more suggestions.
Would appreciate momo5502 review as well.

2022-08-18 16:03 UTC, diamante0018 commented on src/services/kill_list.cpp
> +	{
negate if statement. shorten the nesting. everywhere in your code possibly.

2022-08-18 16:03 UTC, diamante0018 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
why all caps?

2022-08-18 16:47 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
does it need justification? i find it easier to read in a filesystem when important files or configuration files are all caps

2022-08-18 16:50 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
plus allcap KILL.TXT is very scary, it will frighten cheaters, i guarantee

2022-08-18 16:56 UTC, diamante0018 commented on src/services/kill_list.cpp
> +		console::info("Could not find %s, no kill list will be loaded.", kill_file.data());
return; !!! shorten the nesting

2022-08-18 16:57 UTC, Rackover commented on src/services/kill_list.cpp
> +		console::info("Could not find %s, no kill list will be loaded.", kill_file.data());
😠

2022-08-18 17:30 UTC, diamante0018 commented
squash this at the end, please, 19 commits :P

2022-08-18 17:42 UTC, momo5502 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
nah, all lowercase pls. DOS times have passed, we're in 2020

2022-08-18 17:44 UTC, diamante0018 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
Sweet

2022-08-18 17:46 UTC, diamante0018 commented on src/services/kill_list.cpp
> +	if (any_change)
could also remove else statement here by returning early (you hate now do you?)

2022-08-18 17:49 UTC, Rackover commented on src/services/kill_list.cpp
> +	if (any_change)
i'm not sure this is necessary or an improvement even

2022-08-18 17:50 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./KILL.TXT";
done !

2022-08-18 17:51 UTC, diamante0018 commented on src/services/kill_list.cpp
> +	if (any_change)
if you purely weigh in these situations number of lines, maybe yes.

2022-08-18 18:02 UTC, momo5502 requested changes

2022-08-18 18:02 UTC, momo5502 commented on src/services/kill_list.cpp
> +	std::string contents = utils::io::read_file(kill_file);
there is an all in one function for that -> utils::io::read_file with two args and bool return

2022-08-18 18:04 UTC, momo5502 commented
pls don't mark stuff as resolved. if i commented, i want to resolve it. I'm the reviewer, not you

2022-08-18 18:04 UTC, Rackover commented
no problem

2022-08-18 18:07 UTC, momo5502 commented on src/services/patch_kill_list_command.cpp
> +	auto result = getenv_s(&size, key_buff, 128, key_env_name.data());
you're creating a txt file anyways, so sticking to one scheme makes sense

2022-08-18 18:57 UTC, diamante0018 commented
I don't understand the last commit. To address 1 review, you undid everything I reviewed before: early if statement (no nesting, now there is the wrong format again for the lamba?!.
I'm like asking for the same things three times now.

2022-08-18 20:06 UTC, Rackover commented
![image](https://user-images.githubusercontent.com/33836535/185484635-c49c57b4-1559-4d54-acb5-b9ac70d5903b.png)
> I'll do it myself I guess since I'm probably not being listened to.
@diamante0018 

this is an extremely petty comment! i addressed it each time you mentioned it, why bother going back to edit your message 20 minutes after to add this snarky line? it's just weird

i've worked the whole day; i'm cooling off a bit this evening and having dinner. I'm sorry this 20 minutes delay is unacceptable, it's not that you're not being listened to, it's that i'm doing something else right now.

You have write access so feel free to address formatting as you did if you feel like it is an emergency. I will be back on this PR, if needed, when I have available time.  There are still some changes I need to do that I discussed with snake, so merging will not happen in the minute regardless.

2022-08-18 20:10 UTC, diamante0018 commented
I added in the last comment, not because of the 20 minutes delay, but because I started working on it myself after 20 minutes.
I don't think you had a valid reason to undo all the progress made today hence the comment.

2022-08-19 05:09 UTC, momo5502 commented on src/services/kill_list.cpp
> -				return true;
This is huge. Thanks for addressing that. I failed to spot the UAF here :O

2022-08-19 05:11 UTC, momo5502 commented
Timestamp signing is missing. If that's done it should be fine

2022-08-19 06:34 UTC, Rackover commented
I tested it with the timestamp signing, with a duration within 5 minutes (which works) and outside that window (which gets correctly refused) 🙂  if code is good to you guys we can merge anytime

2022-08-19 06:40 UTC, momo5502 approved these changes
looks good to me, one @diamante0018 approved as well, it can be merged

2022-08-19 07:50 UTC, diamante0018 approved these changes
I filled in for louv with the last commit as she is working right now.
Used std::abs, and used params.join to avoid code duplication.
I now approve of this code.

I used <> instead of "" for the utils because it's the project-wide standard and what c++ guidelines want you to do.

2022-08-19 07:53 UTC, diamante0018 commented
Please use Github squash and merge feature. 🙏

2022-08-19 11:04 UTC, momo5502 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
Why is this in the header?

2022-08-19 11:06 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
i thought that's where constants that were relevant to the whole class belonged, should this be somewhere else?

2022-08-19 11:08 UTC, diamante0018 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
top of the cpp file as constexpr const char*?

2022-08-19 11:10 UTC, momo5502 commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
> i thought that's where constants that were relevant to the whole class belonged, should this be somewhere else?

things that are required by more than one cpp file belong in a header. it's simple as that,

2022-08-19 11:12 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
alright, i didn't notice it was not used anywhere else (it might have been at some point and then not) so I should have put this in the private: section of the header. I'm also noting that on the private: section of this header, by the way, is an unused variable `secret_` that should probably be removed! 😄

2022-08-19 11:13 UTC, momo5502 commented
> Please use Github squash and merge feature. 🙏

i generally don't like squashing. you lose history. if the feature needed 50 iterations and therefore 50 commits, then that's how it is. but i want those iterations in the history. it's not like commits were expensive or anything alike.

2022-08-19 11:14 UTC, Rackover commented on src/services/kill_list.hpp
> +	const std::string kill_file = "./kill.txt";
@diamante0018 if you want to move the variables around (in CPP file as you said for instance) feel free to, i can't test compile on my machine for now so it'll have to wait for tonight otherwise 🙏

2022-08-19 11:21 UTC, diamante0018 commented
> > Please use Github squash and merge feature. 🙏
> 
> i generally don't like squashing. you lose history. if the feature needed 50 iterations and therefore 50 commits, then that's how it is. but i want those iterations in the history. it's not like commits were expensive or anything alike.

I see. I guess for these projects it's not super relevant to use squash.
I moved the thing to the cpp file.

2022-08-19 11:31 UTC, momo5502 commented
will merge it after work

2022-08-19 15:06 UTC, Rackover commented
@snake once you're done with this PR & deployment, please send the server private key to an admin (preferrably Dss0, but Evan might need it too ultimately) so he can start the killin' 🔫     I will be explaining to him how it works & providing with a kill client so until evan is done with the bot, only dss0 (or whoever you give the pkey to) will be able to kill

2022-08-19 15:06 UTC, Rackover commented
i will run tests with dss0 with a local master server instance on my computer to make sure everything is correct before we try any of this live, of course

2022-08-19 17:32 UTC, merged