send multiple responses if the server list size exceeds MTU
XLabsProject/master pull request #443
Opened 2023-02-18 21:22 UTC by Rackover

NOT tested !
I'm not sure how we should test it. Maybe make an artificial master server that has TONS of servers and contact it after hosting it somewhere? Cause MTU only is a thing on wide network, not local network. anyway!  We should see if the client accepts it too (it should)

2023-02-18 21:22 UTC, Rackover commented
Closes #228

2023-02-19 08:00 UTC, diamante0018 requested changes

2023-02-19 08:00 UTC, diamante0018 commented on src/services/getservers_command.cpp
> +	console::log("Sent %d servers in %i parts for game %s:\t%s", prepared_servers.size(), packet_count, game.data(), target.to_string().data());
There is a mistake in this format string
%zu should be used for size()

2023-02-19 08:03 UTC, diamante0018 commented on src/services/getservers_command.hpp
> +		uint64_t address;
Since when the address of 4 bytes no suddenly became a 64 bit integer?
There is already a struct idn network module to represent an address

2023-02-19 08:05 UTC, diamante0018 commented on src/services/getservers_command.hpp
> +		uint64_t address;
Also if the structure is only used once in one cpp file it should be moved to the anonymous namespace inside that cpp file.

2023-02-19 09:37 UTC, momo5502 commented
I aggree with @diamante0018 and have nothing to add.

2023-02-19 09:55 UTC, Rackover commented on src/services/getservers_command.hpp
> +		uint64_t address;
it appeared as ULONG so i didn't give it much more thought. I thought ULONG was uint64_t but i just read up and i got microsoft'd https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/32862b84-f6e6-40f9-85ca-c4faf985b822
I will make it uint32_t instead

2023-02-19 09:56 UTC, Rackover commented on src/services/getservers_command.hpp
> +		uint64_t address;
I don't know how to move this member into an anonymous struct on the C++ file, can you show me what the syntax would be please?

2023-02-19 09:58 UTC, Rackover commented on src/services/getservers_command.hpp
> +		uint64_t address;
(also i think by "since when" you probably meant "why" ? 🙂   the date of the commit is written on the commit itself if you click on it in the Github GUI. Its a change from this PR, you can see it's green on the diff.)

2023-02-19 10:20 UTC, diamante0018 commented on src/services/getservers_command.cpp
> +		response.append(reinterpret_cast<const char*>(&server.address), 4);
I'm sorry if I didn't see this before but I would prefer if you used sizeof(server.address) rather than number 4
Same for the line after.
Now that sizeof will return the correct number it's probably best to do that.

2023-02-19 10:24 UTC, momo5502 requested changes
Does this match the official dpmaster/quake protocol?
What I don't like is that one never knows when all packets have been received.
BOIII has a callback that is invoked once the master server responded. That won't work (reliably) anymore with this mechanism. Although BOIII has so few servers that this won't matter, hence this PR is fine to me, except the two adjustments requested.

2023-02-19 10:24 UTC, momo5502 commented on src/services/getservers_command.cpp
> +		response.append(reinterpret_cast<const char*>(&server.address), 4);
while in general, i would agree with you, we adhere to the dpmaster protocol, which requires 4 bytes, so having 4 hardcoded in here seems fine to me

2023-02-19 10:24 UTC, momo5502 commented on src/services/getservers_command.cpp
> +	int packet_count = 0;
why is this an int tho, and not size_t? can we have negative counts?

2023-02-19 10:24 UTC, momo5502 commented on src/services/getservers_command.cpp
> +	console::log("Sent %zu servers in %i parts for game %s:\t%s", prepared_servers.size(), packet_count, game.data(), target.to_string().data());
%zu parts, as soon as packet_count has been changed to size_t

2023-02-19 10:31 UTC, Rackover commented
> while in general, i would agree with you, we adhere to the dpmaster protocol, which requires 4 bytes, so having 4 hardcoded in here seems fine to me

okay i made a change regarding this, tell me if it pleases you both

2023-02-19 10:35 UTC, Rackover commented
https://github.com/kphillisjr/dpmaster/blob/master/src/messages.c#L592

Not sure i'm reading this correctly but it seems like multiparting is handled similarly ?

2023-02-19 10:41 UTC, diamante0018 commented on src/services/getservers_command.cpp
> +	console::log("Sent %zu servers in %i parts for game %s:\t%s", prepared_servers.size(), packet_count, game.data(), target.to_string().data());
Nice catch 😊

2023-02-19 10:42 UTC, diamante0018 commented on src/services/getservers_command.cpp
> +		response.append(reinterpret_cast<const char*>(&server.address), 4);
I would then propose to add static assertion after the struct definition to ensure it of the correct size. Or yeah hard code it

2023-02-19 10:43 UTC, Rackover commented on src/services/getservers_command.cpp
> +		response.append(reinterpret_cast<const char*>(&server.address), 4);
Check code again, if it's still not good for you guys i will let you come to an agreement before i do any more changes

2023-02-19 10:44 UTC, momo5502 commented on src/services/getservers_command.cpp
> +
good change :D

2023-02-19 10:45 UTC, momo5502 approved these changes

2023-02-19 10:45 UTC, momo5502 commented
As soon as @diamante0018 approved, it can be merged

2023-02-19 10:45 UTC, diamante0018 commented
It's pretty cool dp master protocol supported this already 🌚

2023-02-19 10:47 UTC, diamante0018 approved these changes

2023-02-19 10:48 UTC, Rackover commented
don't you want to test it somehow before merging it ?

2023-02-20 11:17 UTC, diamante0018 commented
snake said it's okay to yolo merge so here we go

2023-02-20 11:23 UTC, Rackover commented
your responsibility then :>

2023-02-20 11:24 UTC, diamante0018 commented
No you

2023-02-20 11:29 UTC, merged